### ISSUE TITLE
uno is not usable, com.sun.* missing, too

### ISSUE THREAD

**Issue by rixx** [moba/spendenquittungsgenerator#2]
I installed `spendenquittungsgenerator` (and hence `uno`) successfully in a normal Python 3.6 venv, but uno is not usable there:

```
>>> import uno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.6/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ModuleNotFoundError: No module named 'base'
```

Is uno Python 3 compatible at all? It doesn't work in a Python 3.5 venv, either.

Also, my system is missing the `com.sun.*` dependencies even though I've got a current libreoffice installed.

**Comment by moba** [comment]
Yes, I've run into the problem also. I was hoping that this was a problem with my own setup and not a general problem. Sounds like uno needs to be able to locate the LibreOffice installation, which it can only do when not locked in a virtualenv? It works for me now, but I did install all the dependencies including uno as system-wide packages from the Debian repositories.

**Comment by moba** [comment]
Looks like the same or a similar issue exists on MacOSX:

```
$ python3.6 receipt.py 
Traceback (most recent call last):
  File "receipt.py", line 47, in <module>
    import uno
  File "/Users/username/spendenquittungsgenerator/spendenquittungsgenerator/env/lib/python3.6/site-packages/uno-0.3.3-py3.6.egg/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ModuleNotFoundError: No module named 'base'
```

**Comment by rixx** [comment]
Closing due to lack of activity.
